<?php


/**
 * This class adds structure of 'person' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat May  9 20:51:00 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PersonMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PersonMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PersonPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PersonPeer::TABLE_NAME);
		$tMap->setPhpName('Person');
		$tMap->setClassname('Person');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('USERNAME', 'Username', 'VARCHAR', true, 64);

		$tMap->addColumn('BIO', 'Bio', 'LONGVARCHAR', false, null);

		$tMap->addColumn('IMAGE', 'Image', 'LONGVARCHAR', false, null);

		$tMap->addColumn('NO_FOLLOWERS', 'NoFollowers', 'INTEGER', false, null);

		$tMap->addColumn('FULLNAME', 'Fullname', 'VARCHAR', false, 255);

		$tMap->addColumn('WEBSITE', 'Website', 'LONGVARCHAR', false, null);

		$tMap->addColumn('STATUS', 'Status', 'VARCHAR', true, 255);

	} // doBuild()

} // PersonMapBuilder
