<?php

/**
 * Base class that represents a row from the 'person' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jun  4 20:12:32 2009
 *
 * @package    lib.model.om
 */
abstract class BasePerson extends BaseObject  implements Persistent {


  const PEER = 'PersonPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PersonPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the username field.
	 * @var        string
	 */
	protected $username;

	/**
	 * The value for the bio field.
	 * @var        string
	 */
	protected $bio;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the no_followers field.
	 * @var        int
	 */
	protected $no_followers;

	/**
	 * The value for the fullname field.
	 * @var        string
	 */
	protected $fullname;

	/**
	 * The value for the website field.
	 * @var        string
	 */
	protected $website;

	/**
	 * The value for the status field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $status;

	/**
	 * @var        array Relation[] Collection to store aggregation of Relation objects.
	 */
	protected $collRelationsRelatedByPersonId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRelationsRelatedByPersonId.
	 */
	private $lastRelationRelatedByPersonIdCriteria = null;

	/**
	 * @var        array Relation[] Collection to store aggregation of Relation objects.
	 */
	protected $collRelationsRelatedByFollowingId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRelationsRelatedByFollowingId.
	 */
	private $lastRelationRelatedByFollowingIdCriteria = null;

	/**
	 * @var        array Persontag[] Collection to store aggregation of Persontag objects.
	 */
	protected $collPersontags;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPersontags.
	 */
	private $lastPersontagCriteria = null;

	/**
	 * @var        array Topicperson[] Collection to store aggregation of Topicperson objects.
	 */
	protected $collTopicpersons;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTopicpersons.
	 */
	private $lastTopicpersonCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePerson object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->status = '';
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [username] column value.
	 * 
	 * @return     string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Get the [bio] column value.
	 * 
	 * @return     string
	 */
	public function getBio()
	{
		return $this->bio;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [no_followers] column value.
	 * 
	 * @return     int
	 */
	public function getNoFollowers()
	{
		return $this->no_followers;
	}

	/**
	 * Get the [fullname] column value.
	 * 
	 * @return     string
	 */
	public function getFullname()
	{
		return $this->fullname;
	}

	/**
	 * Get the [website] column value.
	 * 
	 * @return     string
	 */
	public function getWebsite()
	{
		return $this->website;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PersonPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [username] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setUsername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username !== $v) {
			$this->username = $v;
			$this->modifiedColumns[] = PersonPeer::USERNAME;
		}

		return $this;
	} // setUsername()

	/**
	 * Set the value of [bio] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setBio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bio !== $v) {
			$this->bio = $v;
			$this->modifiedColumns[] = PersonPeer::BIO;
		}

		return $this;
	} // setBio()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = PersonPeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Set the value of [no_followers] column.
	 * 
	 * @param      int $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setNoFollowers($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->no_followers !== $v) {
			$this->no_followers = $v;
			$this->modifiedColumns[] = PersonPeer::NO_FOLLOWERS;
		}

		return $this;
	} // setNoFollowers()

	/**
	 * Set the value of [fullname] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setFullname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fullname !== $v) {
			$this->fullname = $v;
			$this->modifiedColumns[] = PersonPeer::FULLNAME;
		}

		return $this;
	} // setFullname()

	/**
	 * Set the value of [website] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setWebsite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->website !== $v) {
			$this->website = $v;
			$this->modifiedColumns[] = PersonPeer::WEBSITE;
		}

		return $this;
	} // setWebsite()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     Person The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v || $v === '') {
			$this->status = $v;
			$this->modifiedColumns[] = PersonPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(PersonPeer::STATUS))) {
				return false;
			}

			if ($this->status !== '') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->username = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->bio = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->image = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->no_followers = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->fullname = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->website = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->status = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = PersonPeer::NUM_COLUMNS - PersonPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Person object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PersonPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collRelationsRelatedByPersonId = null;
			$this->lastRelationRelatedByPersonIdCriteria = null;

			$this->collRelationsRelatedByFollowingId = null;
			$this->lastRelationRelatedByFollowingIdCriteria = null;

			$this->collPersontags = null;
			$this->lastPersontagCriteria = null;

			$this->collTopicpersons = null;
			$this->lastTopicpersonCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePerson:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PersonPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePerson:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePerson:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePerson:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PersonPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PersonPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PersonPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PersonPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collRelationsRelatedByPersonId !== null) {
				foreach ($this->collRelationsRelatedByPersonId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRelationsRelatedByFollowingId !== null) {
				foreach ($this->collRelationsRelatedByFollowingId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPersontags !== null) {
				foreach ($this->collPersontags as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTopicpersons !== null) {
				foreach ($this->collTopicpersons as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PersonPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collRelationsRelatedByPersonId !== null) {
					foreach ($this->collRelationsRelatedByPersonId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRelationsRelatedByFollowingId !== null) {
					foreach ($this->collRelationsRelatedByFollowingId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPersontags !== null) {
					foreach ($this->collPersontags as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTopicpersons !== null) {
					foreach ($this->collTopicpersons as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUsername();
				break;
			case 2:
				return $this->getBio();
				break;
			case 3:
				return $this->getImage();
				break;
			case 4:
				return $this->getNoFollowers();
				break;
			case 5:
				return $this->getFullname();
				break;
			case 6:
				return $this->getWebsite();
				break;
			case 7:
				return $this->getStatus();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PersonPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUsername(),
			$keys[2] => $this->getBio(),
			$keys[3] => $this->getImage(),
			$keys[4] => $this->getNoFollowers(),
			$keys[5] => $this->getFullname(),
			$keys[6] => $this->getWebsite(),
			$keys[7] => $this->getStatus(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUsername($value);
				break;
			case 2:
				$this->setBio($value);
				break;
			case 3:
				$this->setImage($value);
				break;
			case 4:
				$this->setNoFollowers($value);
				break;
			case 5:
				$this->setFullname($value);
				break;
			case 6:
				$this->setWebsite($value);
				break;
			case 7:
				$this->setStatus($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PersonPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsername($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBio($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setImage($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNoFollowers($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFullname($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setWebsite($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setStatus($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PersonPeer::DATABASE_NAME);

		if ($this->isColumnModified(PersonPeer::ID)) $criteria->add(PersonPeer::ID, $this->id);
		if ($this->isColumnModified(PersonPeer::USERNAME)) $criteria->add(PersonPeer::USERNAME, $this->username);
		if ($this->isColumnModified(PersonPeer::BIO)) $criteria->add(PersonPeer::BIO, $this->bio);
		if ($this->isColumnModified(PersonPeer::IMAGE)) $criteria->add(PersonPeer::IMAGE, $this->image);
		if ($this->isColumnModified(PersonPeer::NO_FOLLOWERS)) $criteria->add(PersonPeer::NO_FOLLOWERS, $this->no_followers);
		if ($this->isColumnModified(PersonPeer::FULLNAME)) $criteria->add(PersonPeer::FULLNAME, $this->fullname);
		if ($this->isColumnModified(PersonPeer::WEBSITE)) $criteria->add(PersonPeer::WEBSITE, $this->website);
		if ($this->isColumnModified(PersonPeer::STATUS)) $criteria->add(PersonPeer::STATUS, $this->status);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PersonPeer::DATABASE_NAME);

		$criteria->add(PersonPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Person (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsername($this->username);

		$copyObj->setBio($this->bio);

		$copyObj->setImage($this->image);

		$copyObj->setNoFollowers($this->no_followers);

		$copyObj->setFullname($this->fullname);

		$copyObj->setWebsite($this->website);

		$copyObj->setStatus($this->status);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getRelationsRelatedByPersonId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRelationRelatedByPersonId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRelationsRelatedByFollowingId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRelationRelatedByFollowingId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPersontags() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPersontag($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTopicpersons() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTopicperson($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Person Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PersonPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PersonPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collRelationsRelatedByPersonId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRelationsRelatedByPersonId()
	 */
	public function clearRelationsRelatedByPersonId()
	{
		$this->collRelationsRelatedByPersonId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRelationsRelatedByPersonId collection (array).
	 *
	 * By default this just sets the collRelationsRelatedByPersonId collection to an empty array (like clearcollRelationsRelatedByPersonId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRelationsRelatedByPersonId()
	{
		$this->collRelationsRelatedByPersonId = array();
	}

	/**
	 * Gets an array of Relation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Person has previously been saved, it will retrieve
	 * related RelationsRelatedByPersonId from storage. If this Person is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Relation[]
	 * @throws     PropelException
	 */
	public function getRelationsRelatedByPersonId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRelationsRelatedByPersonId === null) {
			if ($this->isNew()) {
			   $this->collRelationsRelatedByPersonId = array();
			} else {

				$criteria->add(RelationPeer::PERSON_ID, $this->id);

				RelationPeer::addSelectColumns($criteria);
				$this->collRelationsRelatedByPersonId = RelationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RelationPeer::PERSON_ID, $this->id);

				RelationPeer::addSelectColumns($criteria);
				if (!isset($this->lastRelationRelatedByPersonIdCriteria) || !$this->lastRelationRelatedByPersonIdCriteria->equals($criteria)) {
					$this->collRelationsRelatedByPersonId = RelationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRelationRelatedByPersonIdCriteria = $criteria;
		return $this->collRelationsRelatedByPersonId;
	}

	/**
	 * Returns the number of related Relation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Relation objects.
	 * @throws     PropelException
	 */
	public function countRelationsRelatedByPersonId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRelationsRelatedByPersonId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RelationPeer::PERSON_ID, $this->id);

				$count = RelationPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RelationPeer::PERSON_ID, $this->id);

				if (!isset($this->lastRelationRelatedByPersonIdCriteria) || !$this->lastRelationRelatedByPersonIdCriteria->equals($criteria)) {
					$count = RelationPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRelationsRelatedByPersonId);
				}
			} else {
				$count = count($this->collRelationsRelatedByPersonId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Relation object to this object
	 * through the Relation foreign key attribute.
	 *
	 * @param      Relation $l Relation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRelationRelatedByPersonId(Relation $l)
	{
		if ($this->collRelationsRelatedByPersonId === null) {
			$this->initRelationsRelatedByPersonId();
		}
		if (!in_array($l, $this->collRelationsRelatedByPersonId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRelationsRelatedByPersonId, $l);
			$l->setPersonRelatedByPersonId($this);
		}
	}

	/**
	 * Clears out the collRelationsRelatedByFollowingId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRelationsRelatedByFollowingId()
	 */
	public function clearRelationsRelatedByFollowingId()
	{
		$this->collRelationsRelatedByFollowingId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRelationsRelatedByFollowingId collection (array).
	 *
	 * By default this just sets the collRelationsRelatedByFollowingId collection to an empty array (like clearcollRelationsRelatedByFollowingId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRelationsRelatedByFollowingId()
	{
		$this->collRelationsRelatedByFollowingId = array();
	}

	/**
	 * Gets an array of Relation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Person has previously been saved, it will retrieve
	 * related RelationsRelatedByFollowingId from storage. If this Person is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Relation[]
	 * @throws     PropelException
	 */
	public function getRelationsRelatedByFollowingId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRelationsRelatedByFollowingId === null) {
			if ($this->isNew()) {
			   $this->collRelationsRelatedByFollowingId = array();
			} else {

				$criteria->add(RelationPeer::FOLLOWING_ID, $this->id);

				RelationPeer::addSelectColumns($criteria);
				$this->collRelationsRelatedByFollowingId = RelationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RelationPeer::FOLLOWING_ID, $this->id);

				RelationPeer::addSelectColumns($criteria);
				if (!isset($this->lastRelationRelatedByFollowingIdCriteria) || !$this->lastRelationRelatedByFollowingIdCriteria->equals($criteria)) {
					$this->collRelationsRelatedByFollowingId = RelationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRelationRelatedByFollowingIdCriteria = $criteria;
		return $this->collRelationsRelatedByFollowingId;
	}

	/**
	 * Returns the number of related Relation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Relation objects.
	 * @throws     PropelException
	 */
	public function countRelationsRelatedByFollowingId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRelationsRelatedByFollowingId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RelationPeer::FOLLOWING_ID, $this->id);

				$count = RelationPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RelationPeer::FOLLOWING_ID, $this->id);

				if (!isset($this->lastRelationRelatedByFollowingIdCriteria) || !$this->lastRelationRelatedByFollowingIdCriteria->equals($criteria)) {
					$count = RelationPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRelationsRelatedByFollowingId);
				}
			} else {
				$count = count($this->collRelationsRelatedByFollowingId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Relation object to this object
	 * through the Relation foreign key attribute.
	 *
	 * @param      Relation $l Relation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRelationRelatedByFollowingId(Relation $l)
	{
		if ($this->collRelationsRelatedByFollowingId === null) {
			$this->initRelationsRelatedByFollowingId();
		}
		if (!in_array($l, $this->collRelationsRelatedByFollowingId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRelationsRelatedByFollowingId, $l);
			$l->setPersonRelatedByFollowingId($this);
		}
	}

	/**
	 * Clears out the collPersontags collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPersontags()
	 */
	public function clearPersontags()
	{
		$this->collPersontags = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPersontags collection (array).
	 *
	 * By default this just sets the collPersontags collection to an empty array (like clearcollPersontags());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPersontags()
	{
		$this->collPersontags = array();
	}

	/**
	 * Gets an array of Persontag objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Person has previously been saved, it will retrieve
	 * related Persontags from storage. If this Person is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Persontag[]
	 * @throws     PropelException
	 */
	public function getPersontags($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersontags === null) {
			if ($this->isNew()) {
			   $this->collPersontags = array();
			} else {

				$criteria->add(PersontagPeer::PERSON_ID, $this->id);

				PersontagPeer::addSelectColumns($criteria);
				$this->collPersontags = PersontagPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PersontagPeer::PERSON_ID, $this->id);

				PersontagPeer::addSelectColumns($criteria);
				if (!isset($this->lastPersontagCriteria) || !$this->lastPersontagCriteria->equals($criteria)) {
					$this->collPersontags = PersontagPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPersontagCriteria = $criteria;
		return $this->collPersontags;
	}

	/**
	 * Returns the number of related Persontag objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Persontag objects.
	 * @throws     PropelException
	 */
	public function countPersontags(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPersontags === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PersontagPeer::PERSON_ID, $this->id);

				$count = PersontagPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PersontagPeer::PERSON_ID, $this->id);

				if (!isset($this->lastPersontagCriteria) || !$this->lastPersontagCriteria->equals($criteria)) {
					$count = PersontagPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPersontags);
				}
			} else {
				$count = count($this->collPersontags);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Persontag object to this object
	 * through the Persontag foreign key attribute.
	 *
	 * @param      Persontag $l Persontag
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPersontag(Persontag $l)
	{
		if ($this->collPersontags === null) {
			$this->initPersontags();
		}
		if (!in_array($l, $this->collPersontags, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPersontags, $l);
			$l->setPerson($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person is new, it will return
	 * an empty collection; or if this Person has previously
	 * been saved, it will retrieve related Persontags from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Person.
	 */
	public function getPersontagsJoinTag($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersontags === null) {
			if ($this->isNew()) {
				$this->collPersontags = array();
			} else {

				$criteria->add(PersontagPeer::PERSON_ID, $this->id);

				$this->collPersontags = PersontagPeer::doSelectJoinTag($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersontagPeer::PERSON_ID, $this->id);

			if (!isset($this->lastPersontagCriteria) || !$this->lastPersontagCriteria->equals($criteria)) {
				$this->collPersontags = PersontagPeer::doSelectJoinTag($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersontagCriteria = $criteria;

		return $this->collPersontags;
	}

	/**
	 * Clears out the collTopicpersons collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTopicpersons()
	 */
	public function clearTopicpersons()
	{
		$this->collTopicpersons = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTopicpersons collection (array).
	 *
	 * By default this just sets the collTopicpersons collection to an empty array (like clearcollTopicpersons());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTopicpersons()
	{
		$this->collTopicpersons = array();
	}

	/**
	 * Gets an array of Topicperson objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Person has previously been saved, it will retrieve
	 * related Topicpersons from storage. If this Person is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Topicperson[]
	 * @throws     PropelException
	 */
	public function getTopicpersons($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTopicpersons === null) {
			if ($this->isNew()) {
			   $this->collTopicpersons = array();
			} else {

				$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

				TopicpersonPeer::addSelectColumns($criteria);
				$this->collTopicpersons = TopicpersonPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

				TopicpersonPeer::addSelectColumns($criteria);
				if (!isset($this->lastTopicpersonCriteria) || !$this->lastTopicpersonCriteria->equals($criteria)) {
					$this->collTopicpersons = TopicpersonPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTopicpersonCriteria = $criteria;
		return $this->collTopicpersons;
	}

	/**
	 * Returns the number of related Topicperson objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Topicperson objects.
	 * @throws     PropelException
	 */
	public function countTopicpersons(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTopicpersons === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

				$count = TopicpersonPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

				if (!isset($this->lastTopicpersonCriteria) || !$this->lastTopicpersonCriteria->equals($criteria)) {
					$count = TopicpersonPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTopicpersons);
				}
			} else {
				$count = count($this->collTopicpersons);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Topicperson object to this object
	 * through the Topicperson foreign key attribute.
	 *
	 * @param      Topicperson $l Topicperson
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTopicperson(Topicperson $l)
	{
		if ($this->collTopicpersons === null) {
			$this->initTopicpersons();
		}
		if (!in_array($l, $this->collTopicpersons, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTopicpersons, $l);
			$l->setPerson($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person is new, it will return
	 * an empty collection; or if this Person has previously
	 * been saved, it will retrieve related Topicpersons from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Person.
	 */
	public function getTopicpersonsJoinTopic($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTopicpersons === null) {
			if ($this->isNew()) {
				$this->collTopicpersons = array();
			} else {

				$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

				$this->collTopicpersons = TopicpersonPeer::doSelectJoinTopic($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TopicpersonPeer::PERSON_ID, $this->id);

			if (!isset($this->lastTopicpersonCriteria) || !$this->lastTopicpersonCriteria->equals($criteria)) {
				$this->collTopicpersons = TopicpersonPeer::doSelectJoinTopic($criteria, $con, $join_behavior);
			}
		}
		$this->lastTopicpersonCriteria = $criteria;

		return $this->collTopicpersons;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collRelationsRelatedByPersonId) {
				foreach ((array) $this->collRelationsRelatedByPersonId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRelationsRelatedByFollowingId) {
				foreach ((array) $this->collRelationsRelatedByFollowingId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPersontags) {
				foreach ((array) $this->collPersontags as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTopicpersons) {
				foreach ((array) $this->collTopicpersons as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collRelationsRelatedByPersonId = null;
		$this->collRelationsRelatedByFollowingId = null;
		$this->collPersontags = null;
		$this->collTopicpersons = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePerson:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePerson::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePerson
